# Generated by Django 2.2.6 on 2021-07-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210708_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
